# Generated by Django 6.0 on 2025-12-09 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='beneficiaries',
            field=models.ManyToManyField(blank=True, help_text='Who enjoyed this expense?', related_name='benefit_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
